export const ADD_TROLLEY_ITEM = 'ADD_TROLLEY_ITEM';
export const DELETE_TROLLEY_ITEM = 'DELETE_TROLLEY_ITEM';
export const UPDATE_TROLLEY_ITEM = 'UPDATE_TROLLEY_ITEM';

export const ADD_SHOPPING_LIST_ITEM = 'ADD_SHOPPING_LIST_ITEM';
export const DELETE_SHOPPING_LIST_ITEM = 'DELETE_SHOPPING_LIST_ITEM';
export const UPDATE_SHOPPING_LIST_ITEM = 'UPDATE_SHOPPING_LIST_ITEM';
export const CHANGE_INPUT_ITEM_NAME = 'CHANGE_INPUT_ITEM_NAME';