export const alertConstants = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  CLEAR: 'CLEAR'
}

export const GET_TROLLEY = 'GET_TROLLEY';
export const ADD_TROLLEY_ITEM = 'ADD_TROLLEY_ITEM';
export const DELETE_TROLLEY_ITEM = 'DELETE_TROLLEY_ITEM';
export const UPDATE_TROLLEY_ITEM = 'UPDATE_TROLLEY_ITEM';
export const GET_TROLLEY_ITEM_DETAILS = 'GET_TROLLEY_ITEM_DETAILS';

export const ADD_SHOPPING_LIST_ITEM = 'ADD_SHOPPING_LIST_ITEM';
export const DELETE_SHOPPING_LIST_ITEM = 'DELETE_SHOPPING_LIST_ITEM';
export const UPDATE_SHOPPING_LIST_ITEM = 'UPDATE_SHOPPING_LIST_ITEM';
export const CHANGE_INPUT_ITEM_NAME = 'CHANGE_INPUT_ITEM_NAME';

export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  SUBSCRIBE: 'SUBSCRIBE',
  UPDATE_USER_BIO: 'UPDATE_USER_BIO',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE'
}